### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by zzz6519003** [teropa/redux-voting-server#4]
```
➜  redux-voting-server git:(master) ✗ npm start

> voting-server@1.0.0 start /Users/zhengzhongzhao/Develop/javascript/redux-voting-server
> babel-node index.js



```

then nothing happens :+1:

**Comment by zzz6519003** [comment]
sorry for this insanely stupic question

**Comment by jasan-s** [comment]
i'm a node newb, i'm getting the same result . nothing is happening at http://localhost:8080/ its stating site cant be reached

**Comment by zzz6519003** [comment]
notice it's two app
